# Build
FROM registry.access.redhat.com/ubi8/openjdk-11 as builder

COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .
COPY src src

RUN ./mvnw -B package

# Run
FROM registry.access.redhat.com/ubi8/openjdk-11-runtime

COPY --from=builder /home/jboss/target/spring-tasks-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "spring-tasks-0.0.1-SNAPSHOT.jar"]%